[package]
name = "bento"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["sched", "feature", "fs", "mount", "process"] }
clap = { version = "4.5.47", features = ["derive"] }
flate2 = "1.1.2"
tar = "0.4.44"