name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run the specific cli command '...'
        2. With subcommand '....'
        3. And flag '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior vs Actual Behaviors
      description: A clear description of what you expected to happen and what happens.
    validations:
      required: true

  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: What Linux distro and version are you running?
    validations:
      required: true
