name: Development Task
description: Track development work and technical improvements
title: "[DEV] "
labels: ["development"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template for tracking development work, refactoring, and technical improvements.

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: Clear description of what needs to be built/changed/improved.
    validations:
      required: true

  - type: textarea
    id: background-context
    attributes:
      label: Background/Context
      description: Why is this work needed? What's the current state?
    validations:
      required: true

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: What are the key requirements for this task?
      options:
        - label: Requirement 1 (edit this)
        - label: Requirement 2 (edit this)
        - label: Requirement 3 (edit this)

  - type: textarea
    id: technical-approach
    attributes:
      label: Technical Approach
      description: |
        Outline the planned implementation approach:
        - Architecture changes
        - Files to modify
        - New components/modules needed
        - Testing strategy

  - type: input
    id: dependencies
    attributes:
      label: Dependencies
      description: List any blocking issues or related work
      placeholder: "Blocked by #123, Related to #456"

  - type: dropdown
    id: effort-estimate
    attributes:
      label: Estimated Effort
      description: How much work do you think this will take?
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (3-7 days)
        - XL (> 1 week)

  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: What needs to be completed for this task to be considered done?
      options:
        - label: Code implemented and reviewed
        - label: Tests written and passing
        - label: Documentation updated
        - label: Manual testing completed
        - label: Performance considerations addressed

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional technical notes, gotchas, or considerations.
